pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=master
      - author=dependabot[bot]
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: lint"
    actions:
      merge:
        strict: true
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
