queue_rules:
  - name: default
    conditions:
      - author~=^dependabot\[bot\]$
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: lint"

pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=master
      - author~=^dependabot\[bot\]$
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: lint"
    actions:
      queue:
        name: default
        method: merge

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
