queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - author~=^dependabot\[bot\]$
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: lint"
    merge_conditions:
      - author~=^dependabot\[bot\]$
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: lint"
    merge_method: merge

pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: Automatic merge
    conditions: []
    actions:
      queue:
